-- Esquema del observatorio de medios — régimen de medida nuevo (R1–R5).
-- Verificado presente en el proyecto bd_odesocan el 2026-09-10.
--
-- Este fichero documenta y reproduce, de forma idempotente, lo que el pipeline
-- reinstrumentado necesita en la base de datos. No sustituye a las migraciones
-- ya aplicadas: sirve para levantar el esquema desde cero y para saber, sin
-- entrar en el panel de Supabase, qué columna significa qué.
--
-- La contrapartida metodológica está en docs/CUADERNO_METODOLOGICO.md.

-- ── R1 · El denominador ──────────────────────────────────────────────────────
-- Las piezas sin tema ya no se descartan: se guardan con el array vacío. Un
-- array vacío y un NULL no son lo mismo, y la diferencia importa:
--   temas = '{}'   → clasificada, y no cae en ninguno de los 15 temas
--   temas IS NULL  → el clasificador no ha pasado por aquí
-- Quien quiera solo la agenda de ODESOCAN, que filtre en la consulta. La vista
-- pública `v_noticias_medios` ya lo hace por el dashboard.
comment on column medios.noticias.temas is
'Temas asignados por el clasificador. Array VACIO = pieza fuera de la agenda de ODESOCAN; se conserva a proposito porque es el denominador de cualquier medida de saliencia.';

-- ── R3 · Comparabilidad longitudinal ─────────────────────────────────────────
alter table medios.noticias
  add column if not exists clasificador_version text;

comment on column medios.noticias.clasificador_version is
'Huella del clasificador que etiqueto la pieza. NULL = anterior a esta columna. Dos piezas con huellas distintas NO son comparables en una serie temporal.';

-- ── R4 · Fecha real y su procedencia ─────────────────────────────────────────
-- Sin esta columna no se distingue una fecha de publicación de la hora del
-- raspado, y cualquier análisis de precedencia se construye sobre arena.
alter table medios.noticias
  add column if not exists fecha_pub_origen text;

comment on column medios.noticias.fecha_pub_origen is
'De donde salio fecha_pub. sintetica = hora del raspado, NO es fecha de publicacion. url = precision de dia. NULL = anterior a esta columna.';

-- Taxonomía nativa del medio, deducida de la ruta de la URL. Es contra lo que
-- se contrastan los 15 temas del clasificador.
alter table medios.noticias
  add column if not exists seccion text;

create index if not exists noticias_fecha_pub_origen_idx
  on medios.noticias (fecha_pub_origen);

-- ── R2 · Permanencia en portada y prominencia ────────────────────────────────
-- Una fila por pieza y tirada. Vive aparte de `noticias` porque mide otra cosa:
-- `noticias` registra el alta, `observaciones` registra que la pieza seguía
-- destacada. Una pieza que aguanta cuatro días en portada da una fila en
-- `noticias` y dieciséis aquí.
create table if not exists medios.observaciones (
  id           bigint generated by default as identity primary key,
  url_hash     text not null,
  medio        text not null,
  run_id       text not null,
  observado_en timestamptz not null,
  posicion     integer,
  fuente       text not null,
  unique (url_hash, run_id)
);

comment on table medios.observaciones is
'Una fila por pieza vista en cada ejecucion. Mide permanencia y posicion en portada, no el alta.';

comment on column medios.observaciones.posicion is
'Rango dentro del listado de ORIGEN (feed, portada o API), no entre listados. Comparar solo dentro del mismo valor de fuente.';

create index if not exists observaciones_hash_idx  on medios.observaciones (url_hash);
create index if not exists observaciones_run_idx   on medios.observaciones (run_id);
create index if not exists observaciones_medio_idx on medios.observaciones (medio, observado_en);

-- RLS: misma convención que el resto del esquema, lectura pública (la tabla no
-- guarda más que hashes de URL y posiciones) y escritura por conexión directa.
alter table medios.observaciones enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'medios'
      and tablename = 'observaciones'
      and policyname = 'lectura_publica_observaciones'
  ) then
    create policy lectura_publica_observaciones
      on medios.observaciones
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

grant select on medios.observaciones to anon, authenticated;

-- ── Vista pública del dashboard ──────────────────────────────────────────────
-- Aquí es donde se filtra el denominador, no en la ingesta.
create or replace view public.v_noticias_medios as
  select id, titulo, medio, temas, url, fecha_pub, resumen, seccion, fuente, fecha_scrap
  from medios.noticias n
  where temas is not null and cardinality(temas) > 0;
