-- ═══════════════════════════════════════════════════════════════════════════
-- Esquema del observatorio de medios · ODESOCAN
--
-- APLICAR ANTES DE LA SIGUIENTE EJECUCIÓN DEL SCRAPING. Sin esto, el pipeline
-- intentará escribir columnas y tablas que no existen.
--
-- Qué hace cada bloque:
--   1. Documenta `medios.noticias` y `medios.scraping_log`. Son `if not exists`,
--      así que sobre la base actual no cambian nada: están aquí para cerrar la
--      laguna de reproducibilidad de tener el esquema solo dentro de Supabase.
--   2. Añade la columna `seccion` a `medios.noticias`.  ← SÍ cambia la base
--   3. Crea `medios.observaciones`.                     ← SÍ cambia la base
--   4. Rehace la vista pública con el filtro temático.  ← SÍ cambia la base
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Tablas existentes, documentadas ────────────────────────────────────
create table if not exists medios.noticias (
  id          bigint generated by default as identity primary key,
  url         text not null unique,
  url_hash    text not null unique,
  medio       text not null,
  titulo      text not null,
  resumen     text,
  texto_full  text,
  fecha_pub   timestamptz,
  fecha_scrap timestamptz not null default now(),
  fuente      text not null,
  raw_json    jsonb,
  temas       text[]
);

create table if not exists medios.scraping_log (
  id      bigint generated by default as identity primary key,
  medio   text not null,
  inicio  timestamptz not null,
  fin     timestamptz,
  total   integer default 0,
  nuevas  integer default 0,
  errores integer default 0,
  status  text default 'running'
);

-- ── 2. Sección propia del medio ───────────────────────────────────────────
-- La sección que la cabecera asigna al artículo, leída del feed o de la ruta
-- de la URL. Es un dato del medio, no del clasificador: permite contrastar los
-- 15 temas de ODESOCAN contra la taxonomía nativa de cada cabecera, que es la
-- prueba de validez convergente del clasificador.
alter table medios.noticias add column if not exists seccion text;

create index if not exists noticias_seccion_idx on medios.noticias (medio, seccion);

-- El denominador vive aquí: a partir de ahora `temas` puede ser un array vacío
-- (pieza vista y clasificada, pero fuera de la agenda temática de ODESOCAN).
-- Antes esas piezas se borraban, y sin ellas la saliencia no es calculable.
comment on column medios.noticias.temas is
'Temas asignados por el clasificador. Array VACÍO = pieza fuera de la agenda de ODESOCAN; se conserva a propósito porque es el denominador de cualquier medida de saliencia.';

-- ── 3. Observaciones: la permanencia en portada ───────────────────────────
-- `noticias` guarda el ALTA: una fila por URL, la primera vez que se ve.
-- Esta guarda la PERMANENCIA: una fila por pieza y ejecución, mientras siga
-- en portada. Una pieza que aguanta cinco días es más prominente que una que
-- dura dos horas, y esa diferencia es la otra mitad de la saliencia.
create table if not exists medios.observaciones (
  id           bigint generated by default as identity primary key,
  url_hash     text        not null,
  medio        text        not null,
  run_id       text        not null,   -- identificador de la tirada de scraping
  observado_en timestamptz not null,
  posicion     integer,                -- rango dentro de su listado de origen
  fuente       text        not null,   -- 'rss' | 'html' | 'wp_json'
  unique (url_hash, run_id)
);

create index if not exists observaciones_medio_idx on medios.observaciones (medio, observado_en);
create index if not exists observaciones_hash_idx  on medios.observaciones (url_hash);
create index if not exists observaciones_run_idx   on medios.observaciones (run_id);

comment on table medios.observaciones is
'Una fila por pieza vista en cada ejecución. Mide permanencia y posición en portada, no el alta.';
comment on column medios.observaciones.posicion is
'Rango dentro del listado de ORIGEN (feed, portada o API), no entre listados. Comparar solo dentro del mismo valor de `fuente`.';

-- RLS, replicando la convención de las demás tablas del esquema `medios`:
-- lectura pública, escritura reservada a service_role.
alter table medios.observaciones enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'medios'
      and tablename = 'observaciones'
      and policyname = 'lectura_publica_observaciones'
  ) then
    create policy lectura_publica_observaciones
      on medios.observaciones
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

grant select on medios.observaciones to anon, authenticated;
grant select, insert on medios.observaciones to service_role;

-- ── 4. Vista pública del dashboard ────────────────────────────────────────
-- CRÍTICO: `index.html` se alimenta de esta vista. Desde que las piezas sin
-- tema se conservan, la vista TIENE que filtrarlas o el dashboard empezará a
-- contar como noticias piezas que no pertenecen a ninguna temática, inflando
-- los totales por medio.
--
-- Se usa drop + create en lugar de `create or replace` porque la vista actual
-- no está versionada y puede tener otra forma; `create or replace` fallaría si
-- las columnas no coinciden exactamente.
drop view if exists public.v_noticias_medios;

create view public.v_noticias_medios as
select
  n.url,
  n.medio,
  n.titulo,
  n.resumen,
  n.temas,
  n.seccion,
  n.fuente,
  n.fecha_pub,
  n.fecha_scrap
from medios.noticias n
where n.temas is not null
  and cardinality(n.temas) > 0;

comment on view public.v_noticias_medios is
'Vista del dashboard: solo piezas con al menos un tema. El corpus completo, con el denominador, está en medios.noticias.';

grant select on public.v_noticias_medios to anon, authenticated;

-- ── Comprobación tras aplicar ─────────────────────────────────────────────
--   select count(*) from medios.observaciones;                    -- 0 al inicio
--   select column_name from information_schema.columns
--    where table_schema='medios' and table_name='noticias'
--      and column_name='seccion';                                 -- 1 fila
--   select count(*) from public.v_noticias_medios;                -- = piezas con tema
